server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:C:\Work\Repos\Spring\fiapcervejaria;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

